config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles
  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
    end 

    def create
        @article = Article.new(article_params)
 
        @article.save
        redirect_to @article
    end

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Articles</h1>

<head>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <link href="/assets/stylesheets/articles.scss" rel="stylesheet">

</head>

<div class="container">
<table class="table table-hover">
  <thead> 
    <tr>
      <th>Title</th>
      <th>Text</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td><%= article.text %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<br>
<br>

<section class="centered">
 <a class="btn btn-primary" href="/articles/new" role="button">Add Article</a>
  <a class="btn btn-primary" href="/" role="button">Homepage</a>
 </section>

app/views/articles/new.html.erb
<h1>Add a New Article</h1>
<head>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <link href="/assets/stylesheets/welcome.scss" rel="stylesheet">
</head>


<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<br>
<br>
<br>

<section class="centered">
 <a class="btn btn-primary" href="/articles" role="button">Articles</a>
  <a class="btn btn-primary" href="/" role="button">Homepage</a>
 </section>

app/views/articles/show.html.erb
<head>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">

</head>



<p>
    <strong>Title: </strong>
    <%= @article.title %>
</p>

<p>
    <strong>Text: </strong>
    <%= @article.text %>
</p>

<br>
<br>
<br>

<section class="centered">
 <a class="btn btn-primary" href="/articles/new" role="button">Add Article</a>
  <a class="btn btn-primary" href="/" role="button">Homepage</a>
 </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
</head>

<div class="header">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
      </div>
    </div>  
  </div>  
</div>

<h1>
Welcome!
</h1>

<body>
<!-- container fluid refers to the fact that it spans the whole page -->
  <div class="container-fluid">
    <div class="row" id="subheadings">
      <section class="col-xs-12 col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3" id="splash">
        <br>
        <br>
        <br>
        <a class="btn btn-primary" href="/articles" role="button">Articles</a>
        <a class="btn btn-primary" href="/articles/new" role="button">Add Article</a>
      </section>
    </div>    
    </div>
<html>